# Generated by Django 2.2.19 on 2022-03-27 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
